services:
  frontend:
    build:
      context: ./frontend/markbyte
      args:
        VITE_API_URL: "https://markbyte.xyz/api"
        VITE_FRONTEND_URL: "https://markbyte.xyz"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://markbyte.xyz/api
      - VITE_FRONTEND_URL=https://markbyte.xyz

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    environment:
      - RUNNING_IN_DOCKER=true

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

