linters:
  enable:
    - golangci-lint

run:
  deadline: 3m
  tests: true
  skip-dirs:
    - vendor
    - third_party

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 