name: Backend CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          backend/go.sum
          backend/go.mod
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        cd backend
        go mod tidy
        make build

    - name: Test
      run: |
        cd backend
        make test