name: Backend CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - "main"
      - "dev"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: backend/go.sum

    - name: Run GolangCI-Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.63.4
        working-directory: backend
        args: --timeout=3m

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: backend/go.sum

    - name: Restore Go Modules cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          backend/.cache
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}-${{ hashFiles('backend/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Go modules
      run: |
        cd backend
        go mod tidy
        go mod download
    
    - name: Run Tests
      run: |
        cd backend
        go test -v -parallel=4 -timeout=5m ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: backend/go.sum

    - name: Restore Go Modules cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          backend/.cache
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}-${{ hashFiles('backend/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        cd backend
        make build
    
    # - name: Upload binary artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: backend-binary
    #     path: backend/markbyte 