name: Backend CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache-dependency-path: backend/go.sum

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod  # Caching the Go module cache directory
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Go modules  # New step to ensure ~/go/pkg/mod exists
      run: |
        cd backend
        go mod download
        
    - name: Build
      run: |
        cd backend
        go mod tidy
        make build

    - name: Test
      run: |
        cd backend
        make test 