name: Backend CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: backend/go.sum

    - name: Restore Go Modules cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod  # Caching the Go module cache directory
        key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Ensure Go module cache directory exists
      run: mkdir -p ~/go/pkg/mod

    - name: Download Go modules
      run: |
        cd backend
        go mod tidy
        go mod download
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-binary
        path: backend/markbyte 

    - name: Build
      run: |
        cd backend
        make build

    - name: Test
      run: |
        cd backend
        make test 